# Generated by Django 5.2.12 on 2026-03-18 03:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_th', models.CharField(max_length=255, verbose_name='ชื่อเรื่อง (ไทย)')),
                ('student_name', models.CharField(max_length=100, verbose_name='ชื่อผู้จัดทำ')),
                ('academic_year', models.IntegerField(verbose_name='ปีการศึกษา')),
                ('pdf_file', models.FileField(upload_to='pdfs/', verbose_name='ไฟล์ PDF')),
                ('is_approved', models.BooleanField(default=False, verbose_name='อนุมัติการเผยแพร่')),
            ],
        ),
    ]
