# Generated by Django 5.2.12 on 2026-03-18 04:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('research', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='project',
            options={'ordering': ['-academic_year']},
        ),
        migrations.AddField(
            model_name='project',
            name='department',
            field=models.CharField(choices=[('EE', 'สาขาเทคโนโลยีไฟฟ้า'), ('ET', 'สาขาเทคโนโลยีอิเล็กทรอนิกส์'), ('PT', 'สาขาเทคโนโลยีการผลิต'), ('MT', 'สาขาเทคโนโลยีเครื่องกล'), ('CT', 'สาขาเทคโนโลยีคอมพิวเตอร์')], default='CT', max_length=2, verbose_name='สาขาวิชา'),
        ),
        migrations.AlterField(
            model_name='project',
            name='pdf_file',
            field=models.FileField(blank=True, null=True, upload_to='pdfs/', verbose_name='ไฟล์ PDF'),
        ),
    ]
