# Generated by Django 5.2.12 on 2026-03-21 06:46

import django.core.validators
import research.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('research', '0002_alter_project_options_project_department_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='project',
            options={'ordering': ['-academic_year'], 'verbose_name': 'โครงงาน/ผลงานวิชาการ', 'verbose_name_plural': 'โครงงาน/ผลงานวิชาการ'},
        ),
        migrations.AlterField(
            model_name='project',
            name='pdf_file',
            field=models.FileField(default='', upload_to='pdfs/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf']), research.models.validate_file_size], verbose_name='ไฟล์ PDF'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='project',
            name='student_name',
            field=models.CharField(max_length=255, verbose_name='ชื่อผู้จัดทำ'),
        ),
        migrations.AlterField(
            model_name='project',
            name='title_th',
            field=models.CharField(max_length=500, verbose_name='ชื่อโครงการ (ภาษาไทย)'),
        ),
    ]
