# Generated by Django 5.2.12 on 2026-03-23 03:13

import django.core.validators
import research.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('research', '0003_alter_project_options_alter_project_pdf_file_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='abstract',
            field=models.TextField(blank=True, verbose_name='บทคัดย่อ'),
        ),
        migrations.AddField(
            model_name='project',
            name='awards',
            field=models.TextField(blank=True, null=True, verbose_name='รางวัลที่เคยได้รับ'),
        ),
        migrations.AddField(
            model_name='project',
            name='background',
            field=models.TextField(blank=True, verbose_name='ความเป็นมา/หลักการและเหตุผล'),
        ),
        migrations.AddField(
            model_name='project',
            name='discussion',
            field=models.TextField(blank=True, verbose_name='อภิปรายผล'),
        ),
        migrations.AddField(
            model_name='project',
            name='funding_by',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='ผู้สนับสนุนทุนวิจัย'),
        ),
        migrations.AddField(
            model_name='project',
            name='keywords',
            field=models.CharField(blank=True, max_length=255, verbose_name='คำสำคัญ (Keywords)'),
        ),
        migrations.AddField(
            model_name='project',
            name='methodology',
            field=models.TextField(blank=True, verbose_name='วิธีการวิจัย'),
        ),
        migrations.AddField(
            model_name='project',
            name='objectives',
            field=models.TextField(blank=True, verbose_name='วัตถุประสงค์การวิจัย'),
        ),
        migrations.AddField(
            model_name='project',
            name='organization',
            field=models.CharField(default='วิทยาลัยเทคนิคร้อยเอ็ด', max_length=255, verbose_name='หน่วยงาน'),
        ),
        migrations.AddField(
            model_name='project',
            name='other_info',
            field=models.TextField(blank=True, null=True, verbose_name='อื่นๆ'),
        ),
        migrations.AddField(
            model_name='project',
            name='research_type',
            field=models.CharField(blank=True, max_length=100, verbose_name='ประเภทของงานวิจัย'),
        ),
        migrations.AddField(
            model_name='project',
            name='researcher_co1',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='ชื่อนักวิจัยร่วมคนที่ 1'),
        ),
        migrations.AddField(
            model_name='project',
            name='researcher_co2',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='ชื่อนักวิจัยร่วมคนที่ 2'),
        ),
        migrations.AddField(
            model_name='project',
            name='results',
            field=models.TextField(blank=True, verbose_name='ผลการวิจัย'),
        ),
        migrations.AddField(
            model_name='project',
            name='scope',
            field=models.TextField(blank=True, verbose_name='ขอบเขตของการวิจัย'),
        ),
        migrations.AddField(
            model_name='project',
            name='suggestions_next',
            field=models.TextField(blank=True, verbose_name='ข้อเสนอแนะในการทำวิจัยครั้งต่อไป'),
        ),
        migrations.AddField(
            model_name='project',
            name='suggestions_use',
            field=models.TextField(blank=True, verbose_name='ข้อเสนอแนะในการใช้ประโยชน์'),
        ),
        migrations.AddField(
            model_name='project',
            name='theory',
            field=models.TextField(blank=True, verbose_name='ทฤษฎีที่ใช้ในการศึกษา/ที่เกี่ยวข้อง'),
        ),
        migrations.AddField(
            model_name='project',
            name='title_en',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='ชื่อผลงานวิจัย (ภาษาอังกฤษ)'),
        ),
        migrations.AddField(
            model_name='project',
            name='views_count',
            field=models.PositiveIntegerField(default=0, verbose_name='ยอดเข้าชม'),
        ),
        migrations.AlterField(
            model_name='project',
            name='academic_year',
            field=models.IntegerField(verbose_name='ปีที่ผลงานวิจัยเสร็จ (พ.ศ.)'),
        ),
        migrations.AlterField(
            model_name='project',
            name='pdf_file',
            field=models.FileField(blank=True, null=True, upload_to='pdfs/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf']), research.models.validate_file_size], verbose_name='ไฟล์ PDF ฉบับเต็ม'),
        ),
        migrations.AlterField(
            model_name='project',
            name='student_name',
            field=models.CharField(max_length=255, verbose_name='ชื่อนักวิจัยหลัก'),
        ),
        migrations.AlterField(
            model_name='project',
            name='title_th',
            field=models.CharField(max_length=500, verbose_name='ชื่อผลงานวิจัย (ภาษาไทย)'),
        ),
    ]
