# Generated by Django 5.2.12 on 2026-03-23 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('research', '0004_project_abstract_project_awards_project_background_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='research_type',
            field=models.CharField(choices=[('classroom', 'วิจัยในชั้นเรียน'), ('r_d', 'วิจัยและพัฒนา (R&D)'), ('innovation', 'นวัตกรรมและสิ่งประดิษฐ์'), ('survey', 'วิจัยเชิงสำรวจ'), ('other', 'อื่นๆ')], default='innovation', max_length=50, verbose_name='ประเภทของงานวิจัย'),
        ),
    ]
