# Generated by Django 5.2.12 on 2026-03-24 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('research', '0005_alter_project_research_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='download_count',
            field=models.PositiveIntegerField(default=0, verbose_name='ยอดดาวน์โหลด'),
        ),
    ]
