# Generated by Django 5.2.12 on 2026-03-25 06:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('research', '0006_project_download_count'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_type', models.CharField(choices=[('student', 'นักศึกษา'), ('guest', 'บุคคลภายนอก')], default='guest', max_length=10)),
                ('student_id', models.CharField(blank=True, max_length=11, null=True, verbose_name='รหัสนักศึกษา')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'โปรไฟล์ผู้ใช้งาน',
                'verbose_name_plural': 'โปรไฟล์ผู้ใช้งาน',
            },
        ),
    ]
