# Generated by Django 5.2.12 on 2026-03-25 07:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('research', '0007_userprofile'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='email_verified',
            field=models.BooleanField(default=False, verbose_name='ยืนยันอีเมลแล้ว'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='notify_new_project',
            field=models.BooleanField(default=False, verbose_name='แจ้งเตือนผลงานใหม่'),
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.TextField(verbose_name='ความคิดเห็น')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='research.project')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'ความคิดเห็น',
                'verbose_name_plural': 'ความคิดเห็น',
                'ordering': ['-created_at'],
            },
        ),
    ]
