# Generated by Django 5.2.12 on 2026-03-25 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('research', '0008_userprofile_email_verified_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='phone',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='เบอร์โทรศัพท์'),
        ),
    ]
