# Generated by Django 5.2.12 on 2026-04-19 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('research', '0011_remove_userprofile_notify_new_project_project_owner_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='rating',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='rating',
            name='project',
        ),
        migrations.RemoveField(
            model_name='rating',
            name='user',
        ),
        migrations.RemoveField(
            model_name='project',
            name='owner',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='notify_new_project',
            field=models.BooleanField(default=False, verbose_name='แจ้งเตือนผลงานใหม่'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='user_type',
            field=models.CharField(choices=[('student', 'นักศึกษา'), ('guest', 'บุคคลภายนอก')], default='guest', max_length=10),
        ),
        migrations.DeleteModel(
            name='Favorite',
        ),
        migrations.DeleteModel(
            name='Rating',
        ),
    ]
