# Generated by Django 5.2.12 on 2026-04-25 11:56

import django.core.validators
import research.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('research', '0015_comment_parent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='abstract',
            field=models.TextField(verbose_name='บทคัดย่อ'),
        ),
        migrations.AlterField(
            model_name='project',
            name='pdf_file',
            field=models.FileField(default='', upload_to='pdfs/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf']), research.models.validate_file_size], verbose_name='ไฟล์ PDF ฉบับเต็ม'),
            preserve_default=False,
        ),
    ]
