# Generated by Django 5.2.12 on 2026-08-02 08:47

import django.core.validators
from django.db import migrations, models


def backfill_program_from_department(apps, schema_editor):
    Project = apps.get_model('research', 'Project')
    program_by_department = {
        'EE': 'BTECH_ELECTRICAL',
        'ET': 'BTECH_ELECTRONICS',
        'PT': 'BTECH_PRODUCTION',
        'MT': 'BTECH_MECHANICAL',
        'CT': 'BTECH_COMPUTER',
    }
    for department, program in program_by_department.items():
        Project.objects.filter(department=department, program='').update(program=program)


class Migration(migrations.Migration):

    dependencies = [
        ('research', '0018_backfill_uploaded_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='program',
            field=models.CharField(blank=True, choices=[('VC_AUTO', '[ปวช.] ช่างยนต์'), ('VC_EV', '[ปวช.] ยานยนต์ไฟฟ้า'), ('VC_BODY', '[ปวช.] ตัวถังและสีรถยนต์'), ('VC_MACHINE', '[ปวช.] ช่างกลโรงงาน'), ('VC_WELD', '[ปวช.] ช่างเชื่อมโลหะ'), ('VC_MAINT', '[ปวช.] ช่างซ่อมบำรุง'), ('VC_ELEC', '[ปวช.] ช่างไฟฟ้า'), ('VC_ELECTRONICS', '[ปวช.] อิเล็กทรอนิกส์'), ('VC_CONSTRUCTION', '[ปวช.] ช่างก่อสร้าง'), ('VC_ARCH', '[ปวช.] สถาปัตยกรรม'), ('VC_SURVEY', '[ปวช.] เทคนิควิศวกรรมสำรวจ'), ('VC_CIVIL', '[ปวช.] โยธา'), ('VC_COMPUTER', '[ปวช.] ช่างเทคนิคคอมพิวเตอร์'), ('VC_MECHATRONICS', '[ปวช.] เมคคาทรอนิกส์และหุ่นยนต์'), ('HVC_MECHANICAL', '[ปวส.] เทคนิคเครื่องกล'), ('HVC_EV', '[ปวส.] เทคนิคยานยนต์ไฟฟ้า'), ('HVC_BODY', '[ปวส.] เทคโนโลยีอุตสาหกรรมตัวถังและสีรถยนต์'), ('HVC_PRODUCTION', '[ปวส.] เทคนิคการผลิต'), ('HVC_METAL', '[ปวส.] เทคนิคโลหะ'), ('HVC_INDUSTRIAL', '[ปวส.] เทคนิคอุตสาหกรรม'), ('HVC_ELEC', '[ปวส.] ไฟฟ้า'), ('HVC_ELECTRONICS', '[ปวส.] เทคโนโลยีอิเล็กทรอนิกส์'), ('HVC_CIVIL', '[ปวส.] โยธา'), ('HVC_SURVEY', '[ปวส.] เทคนิควิศวกรรมสำรวจ'), ('HVC_ARCH', '[ปวส.] เทคนิคสถาปัตยกรรม'), ('HVC_MECHATRONICS', '[ปวส.] เมคคาทรอนิกส์และหุ่นยนต์'), ('HVC_COMPUTER', '[ปวส.] เทคโนโลยีคอมพิวเตอร์'), ('BTECH_ELECTRONICS', '[ทล.บ.] เทคโนโลยีอิเล็กทรอนิกส์'), ('BTECH_PRODUCTION', '[ทล.บ.] เทคโนโลยีการผลิต'), ('BTECH_MECHANICAL', '[ทล.บ.] เทคโนโลยีเครื่องกล'), ('BTECH_ELECTRICAL', '[ทล.บ.] เทคโนโลยีไฟฟ้า'), ('BTECH_COMPUTER', '[ทล.บ.] เทคโนโลยีคอมพิวเตอร์'), ('BASIC', 'ผลงานแผนกวิชาช่างเทคนิคพื้นฐาน'), ('GENERAL', 'ผลงานแผนกวิชาสามัญสัมพันธ์')], default='', max_length=32, verbose_name='สาขาวิชา'),
        ),
        migrations.RunPython(backfill_program_from_department, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='project',
            name='academic_year',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(2481)], verbose_name='ปีที่ผลงานวิจัยเสร็จ (พ.ศ.)'),
        ),
        migrations.AlterField(
            model_name='project',
            name='department',
            field=models.CharField(choices=[('PT', 'แผนกวิชาช่างกลโรงงาน'), ('CV', 'แผนกวิชาช่างก่อสร้างและโยธา'), ('WL', 'แผนกวิชาช่างโลหะการ'), ('MT', 'แผนกวิชาช่างยนต์'), ('EE', 'แผนกวิชาช่างไฟฟ้ากำลัง'), ('ET', 'แผนกวิชาช่างอิเล็กทรอนิกส์'), ('MR', 'แผนกวิชาช่างเมคคาทรอนิกส์และหุ่นยนต์'), ('BF', 'แผนกวิชาช่างเทคนิคพื้นฐาน'), ('IT', 'แผนกวิชาช่างเทคนิคอุตสาหกรรม'), ('AR', 'แผนกวิชาช่างเทคนิคสถาปัตยกรรม'), ('CT', 'แผนกวิชาเทคโนโลยีคอมพิวเตอร์'), ('GE', 'แผนกวิชาสามัญสัมพันธ์')], default='CT', max_length=2, verbose_name='แผนกวิชา'),
        ),
    ]
